# Generated by Django 5.1.2 on 2024-12-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('SGL', 'SINGLE'), ('TWN', 'TWIN'), ('DBL', 'DOUBLE'), ('TPL', 'TRIPBLE')], max_length=3)),
                ('beds', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.IntegerField()),
                ('service_type', models.CharField(choices=[('FOOD', 'FOOD'), ('WATER', 'WATER'), ('WINE', 'WINE')], max_length=5)),
                ('time_call', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
