# Generated by Django 5.1.2 on 2024-12-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_person_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
