# Generated by Django 5.1.2 on 2024-12-16 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_service_servicebooking_delete_person_delete_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='time_call',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
